### ISSUE TITLE
Update the README description

### ISSUE THREAD

**Issue by qtrandev** [CodeForFtL/ftlviz#3]
Guide on how to write one:
https://github.com/codeforamerica/howto/blob/master/Good-READMEs.md

Sample:
https://github.com/qtrandev/LeafletTransit

**Comment by ryanvgates** [comment]
Just merged in @jehanne32 pull request https://github.com/CodeForFtL/ftlviz/pull/10. Should this be closed now?

**Comment by qtrandev** [comment]
The README is not finished. We need to fill it out more.

**Comment by jehanne32** [comment]
What specifically do you want to add to the README file? Should I add the Code for America copyright symbol? Do you have any screenshots to add? Is there anything that needs to be tested that can be listed? Please let me know if there is anything besides what I have asked that needs to  be added.

**Comment by qtrandev** [comment]
The following is needed:
1) In the Who section, add links to the City of Fort Lauderdale and Code for Fort Lauderdale. Remove "Create by" section.
2) Update the What section - we need to be more descriptive - maybe a whole paragraph. I don't know what to put right now, but make up something based on what you see the map does.
3) Why section. It's to help citizens see construction, for the City to visualize ongoing construction, and for them to see if they can move forward or backward projects so streets can be torn up just once, for possibly adjusting closures and traffic signal timings based on constructions and events.
4) Combine "Why this has been created" into Why section.
5) Screenshots if you can, but I don't know where they can be stored right now. Give them to me and I can upload to qtrandev.com.
6) We need a How sections. Dependencies are:  Leaflet, Font Awesome, Awesome Markers, CartoDB - follow https://github.com/codeforamerica/howto/blob/master/Good-READMEs.md format
7) Add Deploy and License (Code for America license) section.

Misc
1) Remove colons from titles - follow https://github.com/codeforamerica/howto/blob/master/Good-READMEs.md format

I can do these things eventually, but I'm a little slow. You can pick any of those to do.

**Comment by jehanne32** [comment]
Quyen,
I did the first 4 things on your list and also the misc about removing colons. I haven't tried to get any screen shots yet and I can add the Code for America license. 

For the dependencies, do all of these programs need to be loaded to make the site work?
I'll work on this more over the weekend. 

Michelle

```
 On Wednesday, August 12, 2015 12:19 PM, Quyen Tran <notifications@github.com> wrote:
```

 The following is needed:
1) In the Who section, add links to the City of Fort Lauderdale and Code for Fort Lauderdale. Remove "Create by" section.
2) Update the What section - we need to be more descriptive - maybe a whole paragraph. I don't know what to put right now, but make up something based on what you see the map does.
3) Why section. It's to help citizens see construction, for the City to visualize ongoing construction, and for them to see if they can move forward or backward projects so streets can be torn up just once, for possibly adjusting closures and traffic signal timings based on constructions and events.
4) Combine "Why this has been created" into Why section.
5) Screenshots if you can, but I don't know where they can be stored right now. Give them to me and I can upload to qtrandev.com.
6) We need a How sections. Dependencies are: Leaflet, Font Awesome, Awesome Markers, CartoDB - follow https://github.com/codeforamerica/howto/blob/master/Good-READMEs.md format
7) Add Deploy and License (Code for America license) section.Misc
1) Remove colons from titles - follow https://github.com/codeforamerica/howto/blob/master/Good-READMEs.md formatI can do these things eventually, but I'm a little slow. You can pick any of those to do.—

**Comment by qtrandev** [comment]
The changes have been added. We can add screenshots later. Closing item.
